
@api = http://localhost:3000/tasks


GET {{api}}

###
GET {{api}}/5

###
GET {{api}}/count

###
POST {{api}}
Content-Type: application/json

{
    "title" : "tasks 7",
    "description" : "description 7"
}

###
DELETE {{api}}/8


###
PUT {{api}}/1
Content-Type: application/json

{
    "title" : "tasks 1 Modificada"
}